### PR TITLE
Accordion v2

### PR DESCRIPTION
**Pull request by aaronhans**
These changes incorporate the latest version of the CA design system accordion component. 

The latest version of the client side component is a major version bump due to a breaking change where the markup is updated to use the details and summary elements. Any plugin change deployed in a headless setup will have to be coordinated with a frontend update to use the v2 version of the component too

There are a lot of file deletions because this repo used to contain the entire frontend accordion component code

### CODE REVIEW

**Comment by aaronhans** [comment]
This plugin update has been deployed to digital-ca-gov dev instance and is a big improvement on the accordion authoring experience there

**Comment by chachasikes** [comment]
Thanks for this @aaronhans 

Question: 
Does this break markup and accordion rendering? It is recommended that a site admin repair any accordion instances in the content? I expect that it will because I see selector changes that will either cause Gutenberg to give content editor a prompt to update the block, or to cause an error.

In case it breaks: I have a dev branch with some upgrade script code (started) - and did some research on deprecated attributes in Gutenberg blocks. We can provide some tips on finding and fixing markup that will be well served for static & CMS based design system instances alike.

Regarding progressive enhancement: I know you did some recent work based on awesome feedback from other State devs on simplifying the accordion to make it more progressively enhanceable. We have moved most of our other Gutenberg blocks to use attributes that will dynamically render the markup, and which work with attribute upgrades. 

In general, the dynamic option has worked well for our components because our design system will continue to evolve as we get more feedback and improve the designs and features, but we also want to make this as painless as possible for site maintainers.

Any thoughts on switching over to dynamic rendering (and separating the content attributes from the markup attributes)?

Have also been thinking about future reversibility issues - for example  - disabling the block and theme: default to progressively enhanced version - this version of the accordion will degrade if an alternate editing system is chosen at a later date - though there would still be content migration issues to get the markup into any other format. This may be unavoidable, but whatever we can do to simplify it and make it easier to migrate - or move out of WordPress and into another system will likely save future teams time and money.


Next step:
- [ ] Check upgrade on other production instances - understand if markup changes are required in content

**Comment by aaronhans** [comment]
This plugin was already using a dynamic render callback in plugin.php. **Not** doing this causes existing instance component freakout with any markup update so it should be used everywhere. 

My test post with existing accordions automatically updated them to use the new markup without me touching those elements but I did update that post. 

Was there another type of dynamic rendering you were referring to @chachasikes?

**Comment by chachasikes** [comment]
OK - I saw the class based UI elements changed in the review & thought this was still on the old system. Didn't remember if we had moved it - but we did. (Also, feature card is also on this system. I'll review the others to make sure all of the blocks are on the dynamic system.)

So yes the attributes are already set, so changing the class names should not break it.

**Comment by chachasikes** [comment]
FWIW - button-grid is the one that relies only on css & div structure, no attributes.

**Review by zakiya — APPROVED** [review]
This looks okay to me code-wise.

**Pull request merged**
