### PR TITLE
Allow for disabling of Pantheon functionality

### PR DESCRIPTION
**Pull request by claytoncollie**
Adds a filter that defaults to `true`

Will allow another theme or plugin to disable this entire conditional

### CODE REVIEW

**Comment by claytoncollie** [comment]
@chachasikes @aaronhans @Danny-Guzman @chachacalifornia @zakiya 

Hi everyone. 

I know this repo is a bit stale but we are using it on a CaGov site right now. 

I wasn't sure who to contact so tagged everyone I see under the Contributors section.

Would it be possible to merge this PR so I can pull down the latest from `main` and use it on my site?

**Comment by chachasikes** [comment]
@zakiya Assigning this back to you for testing and review. My initial test is working on Pantheon.

**Comment by chachasikes** [comment]
We have more of a response and hope to share it soon.

**Comment by chachasikes** [comment]
Question for @claytoncollie 

We are working on a PR for main.

Question about your implementation of `apply_filters` - Can you tell us a little more about how you are calling this function in the theme. It would be helpful to also test the method you are using.

Also - is this the same reference for the method that you are using?
https://developer.wordpress.org/reference/functions/apply_filters/

cc @zakiya

**Comment by zakiya** [comment]
Also can you clarify what theme you are using?

**Comment by claytoncollie** [comment]
@zakiya @chachasikes 

Yes. This is the WordPress Core `apply_filters` function that you linked to earlier. We will call this filter on the `init` hook like so.

```
add_action( 'init', function() {
    add_filter( 'cagov_gb_is_pantheon', '__return_false' );
} );
```

We are using a custom theme forked from [this repository](https://github.com/10up/wp-scaffold). The only thing we need from this plugin is the blocks. All of the other features will be disabled.

**Pull request merged**
