### PR TITLE
Plugin name refactor & set Gutenberg block category for design system.

### PR DESCRIPTION
**Pull request by chachasikes**
* Rename plugin code and constants to match github name (and make everything consistent so category works more cleanly)
* Assign new category (CA Design System) to all blocks and patterns.
* Bump CA Design System category to top of list in GB block picker.

Set plugin version to 1.0.1.

### CODE REVIEW

**Comment by chachasikes** [comment]
With the blocks loaded & bumped up to the top of the interface (when you click the default blue + icon), all our blocks are grouped in a category, so we can find them (and also speed up development and testing.)

Screen Shot 2021-06-05 at 12 40 15 PM

@aaronhans  @wrendo  @kkoryaka @m-sullivan7  @adam-little 

A preview is auto generated from the plugin code - this might be what "Example" is, and we will want to provide sensible defaults for our blocks. This will help the UX & onboarding content editors.

We can look into ordering the elements. Based on what I can see from the Gutenberg Blocks API, there is a lot of potential tailoring that can happen (over time) to improve the interface.

**Comment by chachasikes** [comment]
Right now they are alphabetical.

**Comment by m-sullivan7** [comment]
Wow, this is really cool! Great work Chach!

**Review by aaronhans — APPROVED** [review]
very nice

**Comment by aaronhans** [comment]
Did you already review the existing core WordPress twitter and button components? I hoped those would be good enough for 7/1.

**Pull request merged**
